upstream b0293e5 - Nov 23, 2009

diff --git a/qemu/configure b/qemu/configure
--- a/qemu/configure
+++ b/qemu/configure
@@ -169,15 +169,17 @@ case "$cpu" in
   ;;
 esac
 
-# Default value for a variable defining feature "foo"
-#  * foo="no", feature will only be used if --enable-foo arg is given
-#  * foo="", feature will be searched for, and if found, will be used
-#  * foo="yes", this value vill only be set by --enable-foo flag.
-#                   feature will searched for, if not found, configure exits with error
+# Default value for a variable defining feature "foo".
+#  * foo="no"  feature will only be used if --enable-foo arg is given
+#  * foo=""    feature will be searched for, and if found, will be used
+#              unless --disable-foo is given
+#  * foo="yes" this value will only be set by --enable-foo flag.
+#              feature will searched for,
+#              if not found, configure exits with error
 #
-# Always add --enable-foo and --disable-foo command line args.  Distributions want
-# to ensure that several features are compiled in, and it is impossible without a
-# --enable-foo that exits if feature is not found
+# Always add --enable-foo and --disable-foo command line args.
+# Distributions want to ensure that several features are compiled in, and it
+# is impossible without a --enable-foo that exits if a feature is not found.
 
 bluez=""
 brlapi=""
@@ -1165,9 +1167,9 @@ for drv in $audio_drv_list; do
     ;;
 
     pa)
-    audio_drv_probe $drv pulse/simple.h -lpulse-simple \
+    audio_drv_probe $drv pulse/simple.h "-lpulse-simple -lpulse" \
         "pa_simple *s = NULL; pa_simple_free(s); return 0;"
-    libs_softmmu="-lpulse-simple $libs_softmmu"
+    libs_softmmu="-lpulse -lpulse-simple $libs_softmmu"
     audio_pt_int="yes"
     ;;
 
@@ -1585,7 +1587,7 @@ int main(void)
     return 0;
 }
 EOF
-if $cc $ARCH_CFLAGS -o $TMPE $TMPC 2> /dev/null ; then
+if compile_prog "" "" ; then
   fallocate=yes
 fi
 
@@ -1600,7 +1602,7 @@ int main(void)
     return 0;
 }
 EOF
-if $cc $ARCH_CFLAGS -o $TMPE $TMPC 2> /dev/null ; then
+if compile_prog "" "" ; then
   dup3=yes
 fi
 
@@ -2087,14 +2089,13 @@ esac
 
 tools=
 if test `expr "$target_list" : ".*softmmu.*"` != 0 ; then
-  tools="qemu-img\$(EXESUF) $tools"
+  tools="qemu-img\$(EXESUF) qemu-io\$(EXESUF) $tools"
   if [ "$linux" = "yes" ] ; then
-      tools="qemu-nbd\$(EXESUF) qemu-io\$(EXESUF) $tools"
+      tools="qemu-nbd\$(EXESUF) $tools"
     if [ "$check_utests" = "yes" ]; then
       tools="check-qint check-qstring check-qdict check-qlist $tools"
+      tools="check-qfloat check-qjson $tools"
     fi
-  elif test "$mingw32" = "yes" ; then
-      tools="qemu-io\$(EXESUF) $tools"
   fi
 fi
 echo "TOOLS=$tools" >> $config_host_mak
@@ -2171,14 +2172,26 @@ case "$target" in
     target_softmmu="yes"
     ;;
   ${target_arch2}-linux-user)
+    if test "$linux" != "yes" ; then
+      echo "ERROR: Target '$target' is only available on a Linux host"
+      exit 1
+    fi
     target_user_only="yes"
     target_linux_user="yes"
     ;;
   ${target_arch2}-darwin-user)
+    if test "$darwin" != "yes" ; then
+      echo "ERROR: Target '$target' is only available on a Darwin host"
+      exit 1
+    fi
     target_user_only="yes"
     target_darwin_user="yes"
     ;;
   ${target_arch2}-bsd-user)
+    if test "$bsd" != "yes" ; then
+      echo "ERROR: Target '$target' is only available on a BSD host"
+      exit 1
+    fi
     target_user_only="yes"
     target_bsd_user="yes"
     ;;
@@ -2194,10 +2207,6 @@ mkdir -p $target_dir/tcg
 mkdir -p $target_dir/ide
 if test "$target" = "arm-linux-user" -o "$target" = "armeb-linux-user" -o "$target" = "arm-bsd-user" -o "$target" = "armeb-bsd-user" ; then
   mkdir -p $target_dir/nwfpe
-fi
-
-if test ! -f $target_dir/config-devices.mak ; then
-  cp $source_path/default-configs/${target}.mak $target_dir/config-devices.mak
 fi
 
 #
